# version: "3"
   
# services:
#   db:
#     image: mysql:8
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_DATABASE='mydatabase'
#       - MYSQL_USER='root'
#       - MYSQL_PASSWORD='Aodh1780'
#       - MYSQL_ROOT_PASSWORD='Aodh1780'
#       - MYSQL_HOST=''
#     volumes:
#       - /tmp/app/mysqld:/var/run/mysqld
#       - ./db:/var/lib/mysql
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#       - /tmp/app/mysqld:/run/mysqld
#     depends_on:
#       - db


version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    links: 
      - db
  db:
    image: mysql:5.7
    ports:
      - "3307:3307"
    environment:
      # MYSQL_DATABASE: 'django-app-db'
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'django-app-db'
      MYSQL_USER: 'rootx'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./data/mysql/db:/var/lib/mysql